corpus = "AE = United Arab Emirates\nAF = Afghanistan\nAG = Antigua and Barbuda\nAL = Albania\nAM = Armenia\nAO = Angola\nAR = Argentina\nAT = Austria\nAU = Australia\nAZ = Azerbaijan\nBA = Bosnia and Herzegovina\nBB = Barbados\nBD = Bangladesh\nBE = Belgium\nBF = Burkina Faso\nBG = Bulgaria\nBI = Burundi\nBJ = Benin\nBN = Brunei Darussalam\nBO = Bolivia\nBR = Brazil\nBS = Bahamas\nBT = Bhutan\nBW = Botswana\nBY = Belarus\nBZ = Belize\nCA = Canada\nCD = Congo\nCF = Central African Republic\nCG = Congo\nCH = Switzerland\nCI = Cote d'Ivoire\nCL = Chile\nCM = Cameroon\nCN = China\nCO = Colombia\nCR = Costa Rica\nCU = Cuba\nCV = Cape Verde\nCY = Cyprus\nCZ = Czech Republic\nDE = Germany\nDJ = Djibouti\nDK = Denmark\nDM = Dominica\nDO = Dominican Republic\nDZ = Algeria\nEC = Ecuador\nEE = Estonia\nEG = Egypt\nER = Eritrea\nES = Spain\nET = Ethiopia\nFI = Finland\nFJ = Fiji\nFK = Falkland Islands\nFR = France\nGA = Gabon\nGB = United Kingdom\nGD = Grenada\nGE = Georgia\nGF = French Guiana\nGH = Ghana\nGL = Greenland\nGM = Gambia\nGN = Guinea\nGQ = Equatorial Guinea\nGR = Greece\nGT = Guatemala\nGW = Guinea-Bissau\nGY = Guyana\nHN = Honduras\nHR = Croatia\nHT = Haiti\nHU = Hungary\nID = Indonesia\nIE = Ireland\nIL = Israel\nIN = India\nIQ = Iraq\nIR = Iran\nIS = Iceland\nIT = Italy\nJM = Jamaica\nJO = Jordan\nJP = Japan\nKE = Kenya\nKG = Kyrgyz Republic\nKH = Cambodia\nKM = Comoros\nKN = Saint Kitts and Nevis\nKP = North Korea\nKR = South Korea\nKW = Kuwait\nKZ = Kazakhstan\nLA = Lao People's Democratic Republic\nLB = Lebanon\nLC = Saint Lucia\nLK = Sri Lanka\nLR = Liberia\nLS = Lesotho\nLT = Lithuania\nLV = Latvia\nLY = Libya\nMA = Morocco\nMD = Moldova\nMG = Madagascar\nMK = Macedonia\nML = Mali\nMM = Myanmar\nMN = Mongolia\nMR = Mauritania\nMT = Malta\nMU = Mauritius\nMV = Maldives\nMW = Malawi\nMX = Mexico\nMY = Malaysia\nMZ = Mozambique\nNA = Namibia\nNC = New Caledonia\nNE = Niger\nNG = Nigeria\nNI = Nicaragua\nNL = Netherlands\nNO = Norway\nNP = Nepal\nNZ = New Zealand\nOM = Oman\nPA = Panama\nPE = Peru\nPF = French Polynesia\nPG = Papua New Guinea\nPH = Philippines\nPK = Pakistan\nPL = Poland\nPT = Portugal\nPY = Paraguay\nQA = Qatar\nRE = Reunion\nRO = Romania\nRS = Serbia\nRU = Russian Federationß\nRW = Rwanda\nSA = Saudi Arabia\nSB = Solomon Islands\nSC = Seychelles\nSD = Sudan\nSE = Sweden\nSI = Slovenia\nSK = Slovakia\nSL = Sierra Leone\nSN = Senegal\nSO = Somalia\nSR = Suriname\nST = Sao Tome and Principe\nSV = El Salvador\nSY = Syrian Arab Republic\nSZ = Swaziland\nTD = Chad\nTG = Togo\nTH = Thailand\nTJ = Tajikistan\nTL = Timor-Leste\nTM = Turkmenistan\nTN = Tunisia\nTR = Turkey\nTT = Trinidad and Tobago\nTW = Taiwan\nTZ = Tanzania\nUA = Ukraine\nUG = Uganda\nUS = United States of America\nUY = Uruguay\nUZ = Uzbekistan\nVE = Venezuela\nVN = Vietnam\nVU = Vanuatu\nYE = Yemen\nZA = South Africa\nZM = Zambia\nZW = Zimbabwe"
hashmap = ""

code_country = corpus.split("\n")
code_country = [c.replace("=", ":") for c in code_country]
s = {}
for cc in code_country:
	x = cc.split(":")
	code = x[0].strip().lower()
	country = x[1].strip().lower()
	s[code] = country

print(s)